M48
; DRILL file {KiCad (7.0.0-0)} date Thursday, March 23, 2023 at 08:34:04 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-23T20:34:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.785Y-1.26
X3.785Y-3.18
X5.535Y-1.255
X5.54Y-3.195
T0
M30
